//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomMVVM.MVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автосамосвал
    {
        public int ID { get; set; }
        public string Модель { get; set; }
        public Nullable<double> Грузоподъёмность__т { get; set; }
        public Nullable<double> Время_разгрузки__мин { get; set; }
    }
}
