//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomMVVM.MVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отчет
    {
        public int ID { get; set; }
        public Nullable<int> ID_бульдозера { get; set; }
        public Nullable<int> ID_грунта { get; set; }
        public Nullable<int> Необходимое_количество_бульдозеров { get; set; }
        public Nullable<double> Рабочий_цикл_бульдозера { get; set; }
        public Nullable<double> Объем_призмы_волочения { get; set; }
        public Nullable<double> Длина_отвала_бульдозера { get; set; }
        public Nullable<double> Высота_отвала_бульдозера { get; set; }
        public Nullable<double> Производительность_бульдозера { get; set; }
        public Nullable<int> Количество_автосамосвалов { get; set; }
        public Nullable<double> Длина_передвижения_грунта { get; set; }
    
        public virtual Бульдозер Бульдозер { get; set; }
        public virtual Грунт Грунт { get; set; }
    }
}
